# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor=torch.rand(7,7)
random_tensor

tensor([[0.6334, 0.6604, 0.4897, 0.5576, 0.5778, 0.0603, 0.3479],
        [0.7488, 0.6439, 0.0074, 0.1476, 0.2161, 0.0634, 0.8040],
        [0.6197, 0.4087, 0.7592, 0.3721, 0.4777, 0.3605, 0.7588],
        [0.2234, 0.3301, 0.2761, 0.5144, 0.4790, 0.4576, 0.5013],
        [0.1682, 0.4441, 0.0225, 0.2114, 0.3935, 0.9418, 0.4909],
        [0.6156, 0.7304, 0.3061, 0.0776, 0.9580, 0.8712, 0.0598],
        [0.3310, 0.4507, 0.3221, 0.3370, 0.9320, 0.2283, 0.9244]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor1=torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(random_tensor,random_tensor1.T)

tensor([[1.8439],
        [1.3761],
        [1.8484],
        [1.1986],
        [1.1618],
        [2.1610],
        [1.6553]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(42)
# Create two random tensors
random_tensor_2=torch.rand(2,2)
random_torch_3=torch.rand(2,2)
# Matrix multiply tensors
torch.matmul(random_tensor_2,random_torch_3)

tensor([[0.5792, 1.2563],
        [0.3956, 0.9914]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(42)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.cuda.manual_seed(1234)
# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
random_tensor_3=torch.rand(2,3)
random_tensor_4=torch.rand(2,3)

True



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
mult=torch.matmul(random_tensor_3,random_tensor_4.T)
mult

tensor([[1.5819, 1.1618],
        [1.3159, 0.9286]])

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
torch.max(mult)
# Find min
torch.min(mult)

tensor(0.9286)

### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
torch.argmax(mult)

# Find arg min
torch.argmin(mult)

tensor(3)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
torch.manual_seed(42)
# Create random tensor
new_shape_tensor=torch.rand(1,1,1,10)
# Remove single dimensions
remove_dim=new_shape_tensor.squeeze
# Print out tensors and their shapes
new_shape_tensor,remove_dim

(tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
            0.9408, 0.1332]]]]),
 torch.Size([10]))